### ISSUE TITLE
vind het thee kransje

### ISSUE THREAD

**Issue by maartenmarx** [blindeboom/afstudeerproject#2]
1. Plot per lid het aantal reacties, en orden de leden op aantal reacties.
   * doe eens loglog en kijk of het een rechte lijn.
2. bereken ook per lid het aantal correspondenten op wie ze reageren
3. per lid, hoe vaak de auteur van het stuk op zijn reactie heeft gereageerd

Op basis hiervan maak jij een mooie verzameling leden met ongeveer evenveel reacties, en flink wat reacties waarop we auteursherkenning gaan doen.

**Comment by blindeboom** [comment]
3. Door het hashen van de auteurs, is het lastig om te achterhalen of de reactie van een lid of van de auteur van het stuk was
